/**
 * Desc: Generate the list of voters based on the ages of the people 
 * @author MANASA KAITHA
 *
 */
import java.util.*;

public class Voters {
	public static void main(String[] args) {
		//TODO autogenerated method stub
		Scanner sc=new Scanner(System.in);
		Map<Integer,Integer> vote=new HashMap<Integer,Integer>();
		char choice='n';
		int count=0;
		do {
			//providing the input like id, age of the voters.
			System.out.println("Enter the id : ");
			int id=sc.nextInt();
			System.out.println("Enter the age");
			int age=sc.nextInt();
			vote.put(id, age);
			System.out.println("Want to continue ?");
			//checking for the condition of count of eligible voters
			if(sc.next().charAt(0)=='n')
				count=1;
			}while(count!=1);
		List<Integer> voter=votersList(vote);
		//displays the eligible voters
		System.out.println("Eligible voters are :");
		for(int i=0;i<voter.size();i++)
			System.out.println(voter.get(i));
	}
	
	public static List<Integer> votersList(Map<Integer,Integer> map){
			List<Integer> voterslist=new ArrayList<Integer>();
			//providing the condition whether the person is elligible for vote or not 
			//and also returns the voter list 
			for (Map.Entry<Integer, Integer> entry : map.entrySet()) {
			    if(entry.getValue()>18)
			    	voterslist.add(entry.getKey());
			}
			return voterslist;
		}
}